server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: service_logs
    pipeline_stages:
      - json:
          expressions:
            level: level
            timestamp: ts
            message: msg
            service: service
            id: id
            body: body
            method: method
            path: path
            url: url
            code: code
      - timestamp:
          source: timestamp
          format: RFC3339Nano
      - labels:
          level:
          service:
          code:
    static_configs:
      - targets:
          - localhost
        labels:
          job: json_logs
          __path__: /var/log/*.log