global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  # - job_name: 'tempo'
  #   static_configs:
  #     - targets: [ 'tempo:3200' ]
  - job_name: "gateway"
    static_configs:
      - targets: ["gateway:3333"]
  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"]
  - job_name: "mapper"
    static_configs:
      - targets: ["mapper:1111"]
  - job_name: "redirect"
    static_configs:
      - targets: ["redirect:2222"]
  - job_name: "analytic"
    static_configs:
      - targets: ["analytic:4444"]
